insert into insurance.ainsurance_client values (1, 'ivan', 'petrov');
insert into insurance.insurance_client values (2, 'petr', 'petrov');
insert into insurance.insurance_client values (3, 'sidr', 'petrov');
insert into insurance.personal_policy values (1,1,0,'car', 'insurance of a car');
insert into insurance.personal_policy values (2,2,0,'car', 'insurance of a car');
insert into insurance.personal_policy values (3,3,0,'car', 'insurance of a car');
insert into insurance.personal_policy values (4,1,0,'home', 'insurance of a home');
insert into insurance.personal_policy values (5,2,0,'home', 'insurance of a home');
    insert into insurance.personal_policy values (6,3,0,'home', 'insurance of a home');
    insert into insurance.insurance_client_police values (1,1);
insert into insurance.insurance_client_police values (2,2);
insert into insurance.insurance_client_police values (3,3);
insert into insurance.insurance_client_police values (1,4);
insert into insurance.insurance_client_police values (2,5);
insert into insurance.insurance_client_police values (3,6);